### PR TITLE
Login by stubbing the API response

### PR DESCRIPTION
**Pull request by benjamin-thomas**
@geromegrignon @ChrisZie 

Please have a look at this.

I've been thinking... Considering we don't have access in a practical way to the backend API (we can't reset or seed data, etc.), maybe we should stub every API request instead? That could make implementing certain UI scenarios easier, and it turns out that Cypress has an "intercept" feature baked in.

Now I wouldn't do this normally, but since the API is strictly defined already, maybe that'd be an ok compromise. And also, we don't really care about having a 100% fully operational application (if the API server is down, it's no big deal).

### CODE REVIEW

**Comment by geromegrignon** [comment]
I would be able to provide a clean environment to test the demo with Heroku, but most of the usage of the tests will be made by community implementations we don't have control over.

I agree about stubs requests.

**Comment by benjamin-thomas** [comment]
Alright. If stubbing looks good to you, I'll try to see how far I can go with this approach.

For v2, it may be a good idea to provide specific API endpoints to allow setting up specific test data.

@geromegrignon  I'm confused about the workflow we should adopt in this repo. Are you meant to merge our pull requests or should I review and merge @ChrisZie's work and vice versa?

**Comment by geromegrignon** [comment]
Good catch!

I was about to explicitly define roles.
My role for this repository is to provide insights into the RealWorld project itself.
I don't want to be a gatekeeper about how to achieve e2e testing.
I encourage you to review PRs and merge them when they match your expectations.
However, don't hesitate to ping me if you can't find a consensus on a given task.

@ChrisZie  @benjamin-thomas
If it's fine with you, I would like to promote your participation by adding you as maintainers in the RealWorld README: https://github.com/gothinkster/realworld#active-maintainers by adding an **e2e testing** section.

**Comment by benjamin-thomas** [comment]
@geromegrignon got ya, I'll ping you when necessary then. And yes please add me to the maintainers list. I'm interested in exploring different technologies so I'll probably stick around for a while. 

@ChrisZie looks like you're busy, let me know if that's sounds good to you.

**Comment by benjamin-thomas** [comment]
@geromegrignon, @ChrisZie does not respond so if that's okay with you I'll work and push straight to master this week-end.

**Comment by geromegrignon** [comment]
@benjamin-thomas, sure. This way you'll have a starting point to move forward.

**Pull request merged**
